### ISSUE TITLE
  File "/opt/pre_cache.py", line 236, in <module>

### ISSUE THREAD

**Issue by codgo** [jagerzhang/Pre-cache#4]
站点地图：https://www.progogame.com/sitemap.xml
并发数量：20
超时时间：10秒
缓存标识：cf-cache-status
UA  标识：Pre-cache/python-requests/2.22.0
预缓存开始:
---------------------------------------------------------
Traceback (most recent call last):
  File "/opt/pre_cache.py", line 236, in <module>
    pre.start()
  File "/opt/pre_cache.py", line 122, in start
    urls = self.get_urls()
  File "/opt/pre_cache.py", line 92, in get_urls
    for u in xmltodict.parse(sitemap)["urlset"]["url"]:
KeyError: 'urlset'

**Comment by jagerzhang** [comment]
你这个格式感觉不是标准sitemap格式，你看看我站点的格式：https://zhangge.net/sitemap.xml
一定要用你这个格式，得改下代码适配才行。

**Comment by jagerzhang** [comment]
已兼容各种sitemap格式。
